-- DROP TABLE IF EXISTS staffs;

CREATE TABLE staffs (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);